/**
 * Learning path definitions for the language section.
 *
 * Each path determines which items are included, how many levels exist,
 * and the pacing of content introduction (kana, vocab, grammar, sentences).
 *
 * Path JSON files generated by `scripts/build-language-levels.mjs` contain
 * the actual item-to-level assignments for each path.
 */

export type PathId = "n5" | "conversational" | "n1" | "completionist";

export interface PathPacing {
	/** Number of levels dedicated primarily to kana learning */
	kanaLevels: number;
	/** [min, max] vocabulary items per level (target, not hard limit) */
	vocabDensity: [number, number];
	/** First level where grammar items appear */
	grammarIntroLevel: number;
	/** First level where conjugation items appear */
	conjugationIntroLevel: number;
	/** First level where sentence items appear */
	sentenceIntroLevel: number;
}

export interface LearningPath {
	id: PathId;
	label: string;
	description: string;
	/** Which JLPT levels are included (e.g., ["N5"], ["N5","N4","N3"]) */
	jlptScope: string[];
	/** Total number of levels in this path */
	maxCoreLevels: number;
	/** If set, only include vocab with frequency_rank <= this value */
	frequencyCutoff?: number;
	/** Whether to include items without a JLPT tag */
	includeUntagged: boolean;
	/** Per-path pacing configuration */
	pacing: PathPacing;
}

export const LEARNING_PATHS: Record<PathId, LearningPath> = {
	n5: {
		id: "n5",
		label: "JLPT N5",
		description:
			"Master the basics. Covers all kana, ~2,400 common words, and foundational grammar for the N5 exam.",
		jlptScope: ["N5"],
		maxCoreLevels: 60,
		includeUntagged: false,
		pacing: {
			kanaLevels: 8,
			vocabDensity: [20, 30],
			grammarIntroLevel: 9,
			conjugationIntroLevel: 9,
			sentenceIntroLevel: 12,
		},
	},
	conversational: {
		id: "conversational",
		label: "Conversational",
		description:
			"Everyday fluency. High-frequency words from N5 through N3, prioritized by real-world usage.",
		jlptScope: ["N5", "N4", "N3"],
		maxCoreLevels: 60,
		frequencyCutoff: 10000,
		includeUntagged: false,
		pacing: {
			kanaLevels: 5,
			vocabDensity: [30, 40],
			grammarIntroLevel: 6,
			conjugationIntroLevel: 6,
			sentenceIntroLevel: 8,
		},
	},
	n1: {
		id: "n1",
		label: "JLPT N1",
		description:
			"Full JLPT mastery. All N5 through N1 vocabulary, grammar, and reading comprehension across 100 levels.",
		jlptScope: ["N5", "N4", "N3", "N2", "N1"],
		maxCoreLevels: 100,
		includeUntagged: false,
		pacing: {
			kanaLevels: 3,
			vocabDensity: [30, 40],
			grammarIntroLevel: 4,
			conjugationIntroLevel: 4,
			sentenceIntroLevel: 5,
		},
	},
	completionist: {
		id: "completionist",
		label: "Completionist",
		description:
			"Learn everything. All 33,000+ items including rare words, advanced grammar, and every sentence.",
		jlptScope: ["N5", "N4", "N3", "N2", "N1"],
		maxCoreLevels: 100,
		includeUntagged: true,
		pacing: {
			kanaLevels: 3,
			vocabDensity: [40, 50],
			grammarIntroLevel: 4,
			conjugationIntroLevel: 4,
			sentenceIntroLevel: 5,
		},
	},
};

export const PATH_IDS: PathId[] = [
	"n5",
	"conversational",
	"n1",
	"completionist",
];

export const DEFAULT_PATH: PathId = "n5";

export function getPath(id: PathId): LearningPath {
	return LEARNING_PATHS[id];
}
